// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distributor.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Tax rate applied to a charge.
    /// </summary>
    public partial class Tax
    {
        /// <summary>
        /// Initializes a new instance of the Tax class.
        /// </summary>
        public Tax()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tax class.
        /// </summary>
        public Tax(string name = default(string), double? appliedRate = default(double?))
        {
            Name = name;
            AppliedRate = appliedRate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "appliedRate")]
        public double? AppliedRate { get; set; }

    }
}
