// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distribution.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Charge
    {
        /// <summary>
        /// Initializes a new instance of the Charge class.
        /// </summary>
        public Charge()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Charge class.
        /// </summary>
        public Charge(System.Guid? chargeId = default(System.Guid?), string chargeName = default(string), bool? isBilled = default(bool?), bool? isProratable = default(bool?), bool? isTaxable = default(bool?), double? quantity = default(double?), System.DateTime? periodFrom = default(System.DateTime?), System.DateTime? periodTo = default(System.DateTime?), double? listPrice = default(double?), double? unitPrice = default(double?), double? lineTotal = default(double?))
        {
            ChargeId = chargeId;
            ChargeName = chargeName;
            IsBilled = isBilled;
            IsProratable = isProratable;
            IsTaxable = isTaxable;
            Quantity = quantity;
            PeriodFrom = periodFrom;
            PeriodTo = periodTo;
            ListPrice = listPrice;
            UnitPrice = unitPrice;
            LineTotal = lineTotal;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeId")]
        public System.Guid? ChargeId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ChargeName")]
        public string ChargeName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsBilled")]
        public bool? IsBilled { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsProratable")]
        public bool? IsProratable { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsTaxable")]
        public bool? IsTaxable { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Quantity")]
        public double? Quantity { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PeriodFrom")]
        public System.DateTime? PeriodFrom { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PeriodTo")]
        public System.DateTime? PeriodTo { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ListPrice")]
        public double? ListPrice { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "UnitPrice")]
        public double? UnitPrice { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "LineTotal")]
        public double? LineTotal { get; private set; }

    }
}
