// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distribution.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Context
    {
        /// <summary>
        /// Initializes a new instance of the Context class.
        /// </summary>
        public Context()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Context class.
        /// </summary>
        public Context(System.Guid? contextId = default(System.Guid?), string contextName = default(string), string hierarchy = default(string), IList<Product> products = default(IList<Product>))
        {
            ContextId = contextId;
            ContextName = contextName;
            Hierarchy = hierarchy;
            Products = products;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContextId")]
        public System.Guid? ContextId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ContextName")]
        public string ContextName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Hierarchy")]
        public string Hierarchy { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Products")]
        public IList<Product> Products { get; private set; }

    }
}
