// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distribution.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Product
    {
        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Product class.
        /// </summary>
        public Product(System.Guid? productId = default(System.Guid?), string productName = default(string), string sku = default(string), IList<Charge> charges = default(IList<Charge>))
        {
            ProductId = productId;
            ProductName = productName;
            Sku = sku;
            Charges = charges;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductId")]
        public System.Guid? ProductId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProductName")]
        public string ProductName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sku")]
        public string Sku { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Charges")]
        public IList<Charge> Charges { get; private set; }

    }
}
