// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distributor.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class AccountsPayable
    {
        /// <summary>
        /// Initializes a new instance of the AccountsPayable class.
        /// </summary>
        public AccountsPayable()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the AccountsPayable class.
        /// </summary>
        public AccountsPayable(System.Guid? clientId = default(System.Guid?), string clientName = default(string), System.DateTime? periodFrom = default(System.DateTime?), System.DateTime? periodTo = default(System.DateTime?), double? subTotal = default(double?), double? grandTotal = default(double?), double? globalRebateTotalDiscount = default(double?), IList<Context> contexts = default(IList<Context>), IList<Product> products = default(IList<Product>), IList<Tax> taxes = default(IList<Tax>))
        {
            ClientId = clientId;
            ClientName = clientName;
            PeriodFrom = periodFrom;
            PeriodTo = periodTo;
            SubTotal = subTotal;
            GrandTotal = grandTotal;
            GlobalRebateTotalDiscount = globalRebateTotalDiscount;
            Contexts = contexts;
            Products = products;
            Taxes = taxes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientId")]
        public System.Guid? ClientId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ClientName")]
        public string ClientName { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PeriodFrom")]
        public System.DateTime? PeriodFrom { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PeriodTo")]
        public System.DateTime? PeriodTo { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "SubTotal")]
        public double? SubTotal { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GrandTotal")]
        public double? GrandTotal { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "GlobalRebateTotalDiscount")]
        public double? GlobalRebateTotalDiscount { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Contexts")]
        public IList<Context> Contexts { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Products")]
        public IList<Product> Products { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Taxes")]
        public IList<Tax> Taxes { get; private set; }

    }
}
