// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distributor.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Fee associated with a charge.
    /// </summary>
    public partial class Fee
    {
        /// <summary>
        /// Initializes a new instance of the Fee class.
        /// </summary>
        public Fee()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Fee class.
        /// </summary>
        public Fee(string name = default(string), double? unitValue = default(double?), double? totalValue = default(double?), bool? isTaxable = default(bool?))
        {
            Name = name;
            UnitValue = unitValue;
            TotalValue = totalValue;
            IsTaxable = isTaxable;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "unitValue")]
        public double? UnitValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "totalValue")]
        public double? TotalValue { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isTaxable")]
        public bool? IsTaxable { get; set; }

    }
}
