// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distributor
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for DistributorService.
    /// </summary>
    public static partial class DistributorServiceExtensions
    {
            /// <summary>
            /// GetPayableCharges
            /// </summary>
            /// <remarks>
            /// Get your payable charges data for a specific billing period.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='date'>
            /// Specify a date within the desired billing period. Default: Today. For
            /// example, if the date is March 17th and your billing period is from the 1st
            /// to the 31st of the month, it will return data from March 1st to March 31st.
            /// </param>
            public static object GetPayableCharges(this IDistributorService operations, System.DateTime? date = default(System.DateTime?))
            {
                return operations.GetPayableChargesAsync(date).GetAwaiter().GetResult();
            }

            /// <summary>
            /// GetPayableCharges
            /// </summary>
            /// <remarks>
            /// Get your payable charges data for a specific billing period.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='date'>
            /// Specify a date within the desired billing period. Default: Today. For
            /// example, if the date is March 17th and your billing period is from the 1st
            /// to the 31st of the month, it will return data from March 1st to March 31st.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetPayableChargesAsync(this IDistributorService operations, System.DateTime? date = default(System.DateTime?), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetPayableChargesWithHttpMessagesAsync(date, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
