// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.Distribution.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Tax
    {
        /// <summary>
        /// Initializes a new instance of the Tax class.
        /// </summary>
        public Tax()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Tax class.
        /// </summary>
        public Tax(string taxNumber = default(string), string name = default(string), double? amount = default(double?), double? appliedRate = default(double?))
        {
            TaxNumber = taxNumber;
            Name = name;
            Amount = amount;
            AppliedRate = appliedRate;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TaxNumber")]
        public string TaxNumber { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Name")]
        public string Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Amount")]
        public double? Amount { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AppliedRate")]
        public double? AppliedRate { get; private set; }

    }
}
