// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Choice
    {
        /// <summary>
        /// Initializes a new instance of the Choice class.
        /// </summary>
        public Choice()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Choice class.
        /// </summary>
        public Choice(string value = default(string), IList<Translation> displayName = default(IList<Translation>))
        {
            Value = value;
            DisplayName = displayName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "displayName")]
        public IList<Translation> DisplayName { get; private set; }

    }
}
