// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CreateSubscriptionsAmendmentParameters
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CreateSubscriptionsAmendmentParameters class.
        /// </summary>
        public CreateSubscriptionsAmendmentParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CreateSubscriptionsAmendmentParameters class.
        /// </summary>
        public CreateSubscriptionsAmendmentParameters(IList<SubscriptionsAmendmentParameter> subscriptionAmendmentParameters = default(IList<SubscriptionsAmendmentParameter>))
        {
            SubscriptionAmendmentParameters = subscriptionAmendmentParameters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionAmendmentParameters")]
        public IList<SubscriptionsAmendmentParameter> SubscriptionAmendmentParameters { get; set; }

    }
}
