// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomerCatalogItemsPricingInformationDto
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CustomerCatalogItemsPricingInformationDto class.
        /// </summary>
        public CustomerCatalogItemsPricingInformationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CustomerCatalogItemsPricingInformationDto class.
        /// </summary>
        public CustomerCatalogItemsPricingInformationDto(System.Guid customerId, IList<CatalogItemPricingInformationDto> catalogItems)
        {
            CustomerId = customerId;
            CatalogItems = catalogItems;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "catalogItems")]
        public IList<CatalogItemPricingInformationDto> CatalogItems { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (CatalogItems == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CatalogItems");
            }
            if (CatalogItems != null)
            {
                foreach (var element in CatalogItems)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
