// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomerConfiguredPlatforms
    {
        /// <summary>
        /// Initializes a new instance of the CustomerConfiguredPlatforms
        /// class.
        /// </summary>
        public CustomerConfiguredPlatforms()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomerConfiguredPlatforms
        /// class.
        /// </summary>
        public CustomerConfiguredPlatforms(System.Guid customerId, IList<ConfiguredPlatform> configuredPlatforms = default(IList<ConfiguredPlatform>))
        {
            CustomerId = customerId;
            ConfiguredPlatforms = configuredPlatforms;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "configuredPlatforms")]
        public IList<ConfiguredPlatform> ConfiguredPlatforms { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (ConfiguredPlatforms != null)
            {
                foreach (var element in ConfiguredPlatforms)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
