// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomerSubscriptionMetersDto
    {
        /// <summary>
        /// Initializes a new instance of the CustomerSubscriptionMetersDto
        /// class.
        /// </summary>
        public CustomerSubscriptionMetersDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CustomerSubscriptionMetersDto
        /// class.
        /// </summary>
        public CustomerSubscriptionMetersDto(System.Guid? customerId = default(System.Guid?), System.Guid? platformId = default(System.Guid?), IList<SubscriptionMetersDto> subscriptionMeters = default(IList<SubscriptionMetersDto>))
        {
            CustomerId = customerId;
            PlatformId = platformId;
            SubscriptionMeters = subscriptionMeters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "customerId")]
        public System.Guid? CustomerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "platformId")]
        public System.Guid? PlatformId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionMeters")]
        public IList<SubscriptionMetersDto> SubscriptionMeters { get; set; }

    }
}
