// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CustomerSubscriptionsPricingInformation
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CustomerSubscriptionsPricingInformation class.
        /// </summary>
        public CustomerSubscriptionsPricingInformation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CustomerSubscriptionsPricingInformation class.
        /// </summary>
        public CustomerSubscriptionsPricingInformation(IList<SubscriptionPricingInformation> items = default(IList<SubscriptionPricingInformation>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<SubscriptionPricingInformation> Items { get; set; }

    }
}
