// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Sherweb.Apis.ServiceProvider.Models
{
    public partial class Customer
    {
        internal static Customer DeserializeCustomer(JsonElement element)
        {
            Optional<Guid> id = default;
            Optional<string> displayName = default;
            Optional<IReadOnlyList<string>> path = default;
            Optional<DateTimeOffset?> suspendedOn = default;
            Optional<DateTimeOffset?> deletedOn = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("id"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    id = property.Value.GetGuid();
                    continue;
                }
                if (property.NameEquals("displayName"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        displayName = null;
                        continue;
                    }
                    displayName = property.Value.GetString();
                    continue;
                }
                if (property.NameEquals("path"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<string> array = new List<string>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(item.GetString());
                    }
                    path = array;
                    continue;
                }
                if (property.NameEquals("suspendedOn"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        suspendedOn = null;
                        continue;
                    }
                    suspendedOn = property.Value.GetDateTimeOffset("O");
                    continue;
                }
                if (property.NameEquals("deletedOn"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        deletedOn = null;
                        continue;
                    }
                    deletedOn = property.Value.GetDateTimeOffset("O");
                    continue;
                }
            }
            return new Customer(Optional.ToNullable(id), displayName.Value, Optional.ToList(path), Optional.ToNullable(suspendedOn), Optional.ToNullable(deletedOn));
        }
    }
}
