// <auto-generated>
// This file was auto-generated
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Customers
    {
        /// <summary>
        /// Initializes a new instance of the Customers class.
        /// </summary>
        public Customers()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Customers class.
        /// </summary>
        public Customers(IList<Customer> items = default(IList<Customer>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<Customer> Items { get; set; }

    }
}
