// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Format
    {
        /// <summary>
        /// Initializes a new instance of the Format class.
        /// </summary>
        public Format()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Format class.
        /// </summary>
        public Format(string type = default(string), string pattern = default(string), IList<Choice> choices = default(IList<Choice>))
        {
            Type = type;
            Pattern = pattern;
            Choices = choices;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pattern")]
        public string Pattern { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "choices")]
        public IList<Choice> Choices { get; private set; }

    }
}
