// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetPlatformRequiredParametersRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// GetPlatformRequiredParametersRequest class.
        /// </summary>
        public GetPlatformRequiredParametersRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// GetPlatformRequiredParametersRequest class.
        /// </summary>
        public GetPlatformRequiredParametersRequest(IList<System.Guid?> platformIds)
        {
            PlatformIds = platformIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "platformIds")]
        public IList<System.Guid?> PlatformIds { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (PlatformIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "PlatformIds");
            }
        }
    }
}
