// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlaceOrderRequestV2
    {
        /// <summary>
        /// Initializes a new instance of the PlaceOrderRequestV2 class.
        /// </summary>
        public PlaceOrderRequestV2()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlaceOrderRequestV2 class.
        /// </summary>
        public PlaceOrderRequestV2(IList<CartItemV2> cartItems, string orderedBy = default(string))
        {
            CartItems = cartItems;
            OrderedBy = orderedBy;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cartItems")]
        public IList<CartItemV2> CartItems { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "orderedBy")]
        public string OrderedBy { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (CartItems == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CartItems");
            }
            if (CartItems != null)
            {
                foreach (var element in CartItems)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
