// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformConfiguration
    {
        /// <summary>
        /// Initializes a new instance of the PlatformConfiguration class.
        /// </summary>
        public PlatformConfiguration()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformConfiguration class.
        /// </summary>
        public PlatformConfiguration(System.Guid platformId, IList<RequiredParameter> requiredParameters = default(IList<RequiredParameter>))
        {
            PlatformId = platformId;
            RequiredParameters = requiredParameters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "platformId")]
        public System.Guid PlatformId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredParameters")]
        public IList<RequiredParameter> RequiredParameters { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (RequiredParameters != null)
            {
                foreach (var element in RequiredParameters)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
        }
    }
}
