// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformRequiredParameters
    {
        /// <summary>
        /// Initializes a new instance of the PlatformRequiredParameters class.
        /// </summary>
        public PlatformRequiredParameters()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformRequiredParameters class.
        /// </summary>
        public PlatformRequiredParameters(System.Guid platformId, IList<PlatformRequiredParameter> parameters = default(IList<PlatformRequiredParameter>))
        {
            PlatformId = platformId;
            Parameters = parameters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "platformId")]
        public System.Guid PlatformId { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "parameters")]
        public IList<PlatformRequiredParameter> Parameters { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
