// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformRequiredParameter
    {
        /// <summary>
        /// Initializes a new instance of the PlatformRequiredParameter class.
        /// </summary>
        public PlatformRequiredParameter()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformRequiredParameter class.
        /// </summary>
        public PlatformRequiredParameter(IList<Translation> name = default(IList<Translation>), IList<Translation> description = default(IList<Translation>), string identifier = default(string), string defaultValue = default(string), Format format = default(Format))
        {
            Name = name;
            Description = description;
            Identifier = identifier;
            DefaultValue = defaultValue;
            Format = format;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public IList<Translation> Name { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "description")]
        public IList<Translation> Description { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "identifier")]
        public string Identifier { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "defaultValue")]
        public string DefaultValue { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "format")]
        public Format Format { get; set; }

    }
}
