// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformRequiredParametersCollection
    {
        /// <summary>
        /// Initializes a new instance of the
        /// PlatformRequiredParametersCollection class.
        /// </summary>
        public PlatformRequiredParametersCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// PlatformRequiredParametersCollection class.
        /// </summary>
        public PlatformRequiredParametersCollection(IList<PlatformRequiredParameters> requiredParameters = default(IList<PlatformRequiredParameters>))
        {
            RequiredParameters = requiredParameters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "requiredParameters")]
        public IList<PlatformRequiredParameters> RequiredParameters { get; private set; }

    }
}
