// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformsForSkusCollection
    {
        /// <summary>
        /// Initializes a new instance of the PlatformsForSkusCollection class.
        /// </summary>
        public PlatformsForSkusCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformsForSkusCollection class.
        /// </summary>
        public PlatformsForSkusCollection(IList<SkuPlatforms> skusPlatforms = default(IList<SkuPlatforms>))
        {
            SkusPlatforms = skusPlatforms;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "skusPlatforms")]
        public IList<SkuPlatforms> SkusPlatforms { get; set; }

    }
}
