// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformsCollection
    {
        /// <summary>
        /// Initializes a new instance of the PlatformsCollection class.
        /// </summary>
        public PlatformsCollection()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformsCollection class.
        /// </summary>
        public PlatformsCollection(IList<Platform> platforms = default(IList<Platform>))
        {
            Platforms = platforms;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "platforms")]
        public IList<Platform> Platforms { get; set; }

    }
}
