// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class PlatformDetailsDto
    {
        /// <summary>
        /// Initializes a new instance of the PlatformDetailsDto class.
        /// </summary>
        public PlatformDetailsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PlatformDetailsDto class.
        /// </summary>
        public PlatformDetailsDto(System.Guid platformId, IDictionary<string, string> details)
        {
            PlatformId = platformId;
            Details = details;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "platformId")]
        public System.Guid PlatformId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "details")]
        public IDictionary<string, string> Details { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Details == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Details");
            }
        }
    }
}
