// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PricingInformationDto
    {
        /// <summary>
        /// Initializes a new instance of the PricingInformationDto class.
        /// </summary>
        public PricingInformationDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PricingInformationDto class.
        /// </summary>
        /// <param name="recurringFee">The recurring amount charge every
        /// cycle</param>
        /// <param name="setupFee">The initial amount charge at the end of the
        /// first cycle</param>
        /// <param name="currency">Possible values include: 'Undefined', 'Cad',
        /// 'Usd', 'Eur', 'Gbp'</param>
        /// <param name="billingCycle">A billing cycle, also referred to as a
        /// billing period, is the interval of time between billing statements.
        /// Although billing cycles are most often set at one month, or one
        /// year, they may vary in length depending on the SKU.
        /// Possible values: monthly, yearly, once</param>
        public PricingInformationDto(double recurringFee, double setupFee, string currency, string billingCycle)
        {
            RecurringFee = recurringFee;
            SetupFee = setupFee;
            Currency = currency;
            BillingCycle = billingCycle;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the recurring amount charge every cycle
        /// </summary>
        [JsonProperty(PropertyName = "recurringFee")]
        public double RecurringFee { get; set; }

        /// <summary>
        /// Gets or sets the initial amount charge at the end of the first
        /// cycle
        /// </summary>
        [JsonProperty(PropertyName = "setupFee")]
        public double SetupFee { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Undefined', 'Cad', 'Usd',
        /// 'Eur', 'Gbp'
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or sets a billing cycle, also referred to as a billing period,
        /// is the interval of time between billing statements.
        /// Although billing cycles are most often set at one month, or one
        /// year, they may vary in length depending on the SKU.
        /// Possible values: monthly, yearly, once
        /// </summary>
        [JsonProperty(PropertyName = "billingCycle")]
        public string BillingCycle { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Currency == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Currency");
            }
            if (BillingCycle == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "BillingCycle");
            }
        }
    }
}
