// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using System.Text.Json;
using Azure.Core;

namespace Sherweb.Apis.ServiceProvider.Models
{
    public partial class ReceivableCharges
    {
        internal static ReceivableCharges DeserializeReceivableCharges(JsonElement element)
        {
            Optional<DateTimeOffset> periodFrom = default;
            Optional<DateTimeOffset> periodTo = default;
            Optional<IReadOnlyList<Charge>> charges = default;
            foreach (var property in element.EnumerateObject())
            {
                if (property.NameEquals("periodFrom"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    periodFrom = property.Value.GetDateTimeOffset("D");
                    continue;
                }
                if (property.NameEquals("periodTo"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    periodTo = property.Value.GetDateTimeOffset("D");
                    continue;
                }
                if (property.NameEquals("charges"))
                {
                    if (property.Value.ValueKind == JsonValueKind.Null)
                    {
                        property.ThrowNonNullablePropertyIsNull();
                        continue;
                    }
                    List<Charge> array = new List<Charge>();
                    foreach (var item in property.Value.EnumerateArray())
                    {
                        array.Add(Charge.DeserializeCharge(item));
                    }
                    charges = array;
                    continue;
                }
            }
            return new ReceivableCharges(Optional.ToNullable(periodFrom), Optional.ToNullable(periodTo), Optional.ToList(charges));
        }
    }
}
