// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

// <auto-generated/>

#nullable disable

using System;
using System.Collections.Generic;
using Azure.Core;

namespace Sherweb.Apis.ServiceProvider.Models
{
    /// <summary> All charges to pay for a billing period. </summary>
    public partial class ReceivableCharges
    {
        /// <summary> Initializes a new instance of ReceivableCharges. </summary>
        internal ReceivableCharges()
        {
            Charges = new ChangeTrackingList<Charge>();
        }

        /// <summary> Initializes a new instance of ReceivableCharges. </summary>
        /// <param name="periodFrom"> . </param>
        /// <param name="periodTo"> . </param>
        /// <param name="charges"> . </param>
        internal ReceivableCharges(DateTimeOffset? periodFrom, DateTimeOffset? periodTo, IReadOnlyList<Charge> charges)
        {
            PeriodFrom = periodFrom;
            PeriodTo = periodTo;
            Charges = charges;
        }

        public DateTimeOffset? PeriodFrom { get; }
        public DateTimeOffset? PeriodTo { get; }
        public IReadOnlyList<Charge> Charges { get; }
    }
}
