// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SubscriptionPricingInformation
    {
        /// <summary>
        /// Initializes a new instance of the SubscriptionPricingInformation
        /// class.
        /// </summary>
        public SubscriptionPricingInformation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubscriptionPricingInformation
        /// class.
        /// </summary>
        /// <param name="billingCycle">A billing cycle, also referred to as a
        /// billing period, is the interval of time between billing statements.
        /// Although billing cycles are most often set at one month, or one
        /// year, they may vary in length depending on the SKU.
        /// Possible values: none, daily, weekly, monthly, yearly and
        /// unknown</param>
        public SubscriptionPricingInformation(System.Guid id, string billingCycle, SubscriptionFees fees = default(SubscriptionFees), SubscriptionCommitmentTerm commitmentTerm = default(SubscriptionCommitmentTerm))
        {
            Id = id;
            BillingCycle = billingCycle;
            Fees = fees;
            CommitmentTerm = commitmentTerm;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid Id { get; set; }

        /// <summary>
        /// Gets or sets a billing cycle, also referred to as a billing period,
        /// is the interval of time between billing statements.
        /// Although billing cycles are most often set at one month, or one
        /// year, they may vary in length depending on the SKU.
        /// Possible values: none, daily, weekly, monthly, yearly and unknown
        /// </summary>
        [JsonProperty(PropertyName = "billingCycle")]
        public string BillingCycle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fees")]
        public SubscriptionFees Fees { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commitmentTerm")]
        public SubscriptionCommitmentTerm CommitmentTerm { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (BillingCycle == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "BillingCycle");
            }
            if (Fees != null)
            {
                Fees.Validate();
            }
            if (CommitmentTerm != null)
            {
                CommitmentTerm.Validate();
            }
        }
    }
}
