// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubscriptionsCancellationRequest
    {
        /// <summary>
        /// Initializes a new instance of the SubscriptionsCancellationRequest
        /// class.
        /// </summary>
        public SubscriptionsCancellationRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubscriptionsCancellationRequest
        /// class.
        /// </summary>
        public SubscriptionsCancellationRequest(IList<System.Guid?> subscriptionIds)
        {
            SubscriptionIds = subscriptionIds;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionIds")]
        public IList<System.Guid?> SubscriptionIds { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (SubscriptionIds == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "SubscriptionIds");
            }
        }
    }
}
