// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SubscriptionMetersDto
    {
        /// <summary>
        /// Initializes a new instance of the SubscriptionMetersDto class.
        /// </summary>
        public SubscriptionMetersDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubscriptionMetersDto class.
        /// </summary>
        public SubscriptionMetersDto(System.Guid? subscriptionId = default(System.Guid?), IList<MeterDto> meters = default(IList<MeterDto>))
        {
            SubscriptionId = subscriptionId;
            Meters = meters;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subscriptionId")]
        public System.Guid? SubscriptionId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "meters")]
        public IList<MeterDto> Meters { get; set; }

    }
}
