// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Subscriptions
    {
        /// <summary>
        /// Initializes a new instance of the Subscriptions class.
        /// </summary>
        public Subscriptions()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Subscriptions class.
        /// </summary>
        public Subscriptions(IList<Subscription> items = default(IList<Subscription>))
        {
            Items = items;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<Subscription> Items { get; set; }

    }
}
