// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// Null for subscriptions that have no corresponding catalog item
    /// </summary>
    public partial class SubscriptionFees
    {
        /// <summary>
        /// Initializes a new instance of the SubscriptionFees class.
        /// </summary>
        public SubscriptionFees()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SubscriptionFees class.
        /// </summary>
        /// <param name="recurringFee">The recurring amount charge every
        /// cycle</param>
        /// <param name="setupFee">The initial amount charge at the end of the
        /// first cycle</param>
        /// <param name="currency">Possible values include: 'Undefined', 'Cad',
        /// 'Usd', 'Eur', 'Gbp'</param>
        public SubscriptionFees(double recurringFee, double setupFee, string currency)
        {
            RecurringFee = recurringFee;
            SetupFee = setupFee;
            Currency = currency;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the recurring amount charge every cycle
        /// </summary>
        [JsonProperty(PropertyName = "recurringFee")]
        public double RecurringFee { get; set; }

        /// <summary>
        /// Gets or sets the initial amount charge at the end of the first
        /// cycle
        /// </summary>
        [JsonProperty(PropertyName = "setupFee")]
        public double SetupFee { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Undefined', 'Cad', 'Usd',
        /// 'Eur', 'Gbp'
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Currency == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Currency");
            }
        }
    }
}
