// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class TrackingId
    {
        /// <summary>
        /// Initializes a new instance of the TrackingId class.
        /// </summary>
        public TrackingId()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the TrackingId class.
        /// </summary>
        /// <param name="requestTrackingId">References a request that was made
        /// (order, amendment, cancellation, ...).
        /// Can be used to obtain the request status.</param>
        public TrackingId(System.Guid requestTrackingId)
        {
            RequestTrackingId = requestTrackingId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets references a request that was made (order, amendment,
        /// cancellation, ...).
        /// Can be used to obtain the request status.
        /// </summary>
        [JsonProperty(PropertyName = "requestTrackingId")]
        public System.Guid RequestTrackingId { get; private set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            //Nothing to validate
        }
    }
}
