// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Sherweb.Apis.ServiceProvider.Models
{
    using Microsoft.Rest;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Translation
    {
        /// <summary>
        /// Initializes a new instance of the Translation class.
        /// </summary>
        public Translation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Translation class.
        /// </summary>
        /// <param name="culture">The Two-Letter ISO Language Code (ISO
        /// 639-1)</param>
        public Translation(string culture, string value)
        {
            Culture = culture;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// Gets or sets the Two-Letter ISO Language Code (ISO 639-1)
        /// </summary>
        [JsonProperty(PropertyName = "culture")]
        public string Culture { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Culture == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Culture");
            }
            if (Value == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Value");
            }
        }
    }
}
