// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AuthorizationServer.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Token
    {
        /// <summary>
        /// Initializes a new instance of the Token class.
        /// </summary>
        public Token()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Token class.
        /// </summary>
        public Token(string accessToken = default(string), int? expiresIn = default(int?), string tokenType = default(string))
        {
            AccessToken = accessToken;
            ExpiresIn = expiresIn;
            TokenType = tokenType;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "access_token")]
        public string AccessToken { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "expires_in")]
        public int? ExpiresIn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "token_type")]
        public string TokenType { get; set; }

    }
}
