// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace AuthorizationServer
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for XtklAuthorizationServer.
    /// </summary>
    public static partial class XtklAuthorizationServerExtensions
    {
            /// <summary>
            /// Token
            /// </summary>
            /// <remarks>
            /// Authenticate and get token
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// The registered client ID.
            /// </param>
            /// <param name='clientSecret'>
            /// The registered client ID secret.
            /// </param>
            /// <param name='scope'>
            /// The scope of the token you want.
            /// </param>
            public static Token TokenMethod(this IXtklAuthorizationServer operations, string clientId, string clientSecret, string scope)
            {
                return operations.TokenMethodAsync(clientId, clientSecret, scope).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Token
            /// </summary>
            /// <remarks>
            /// Authenticate and get token
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='clientId'>
            /// The registered client ID.
            /// </param>
            /// <param name='clientSecret'>
            /// The registered client ID secret.
            /// </param>
            /// <param name='scope'>
            /// The scope of the token you want.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<Token> TokenMethodAsync(this IXtklAuthorizationServer operations, string clientId, string clientSecret, string scope, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.TokenMethodWithHttpMessagesAsync(clientId, clientSecret, scope, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
